# Generated by Django 3.1.7 on 2021-03-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of book (e.g. Bhagavad Gita)', max_length=200)),
                ('author', models.CharField(help_text='Enter a name of book (e.g. AC Bhaktivedanta)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PurportPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('child', models.ManyToManyField(related_name='ChildTheme', to='converter.Theme')),
                ('parent', models.ManyToManyField(related_name='ParentTheme', to='converter.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Shloka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canto', models.IntegerField(null=True)),
                ('chapter', models.IntegerField()),
                ('number', models.IntegerField()),
                ('author', models.CharField(max_length=200, null=True)),
                ('translation', models.CharField(max_length=200, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.book')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=100)),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.purportpara')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.theme')),
            ],
        ),
        migrations.AddField(
            model_name='purportpara',
            name='shloka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.shloka'),
        ),
    ]
