# Generated by Django 3.1.7 on 2021-03-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='parent',
        ),
        migrations.AddField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ParentTheme', to='converter.theme'),
        ),
    ]
