# Generated by Django 3.1.7 on 2021-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20210315_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shloka',
            name='author',
        ),
        migrations.AddField(
            model_name='shloka',
            name='text',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shloka',
            name='translation',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
