# Generated by Django 3.1.7 on 2021-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210315_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ManyToManyField(null=True, to='converter.Theme'),
        ),
    ]
