# Generated by Django 3.1.7 on 2021-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20210315_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ManyToManyField(to='converter.Theme'),
        ),
    ]
