# Generated by Django 3.1.7 on 2021-03-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_theme_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='shloka',
            name='purport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.shloka'),
        ),
        migrations.AddField(
            model_name='shloka',
            name='w2w',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
