# Generated by Django 3.1.7 on 2021-03-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20210315_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='purport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='converter.purportpara'),
        ),
    ]
