# Generated by Django 3.1.7 on 2021-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_auto_20210315_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purportpara',
            name='text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
