# Generated by Django 3.1.7 on 2021-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_auto_20210315_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shloka',
            name='purport',
        ),
        migrations.AddField(
            model_name='shloka',
            name='purport',
            field=models.ManyToManyField(related_name='Purport', to='converter.PurportPara'),
        ),
    ]
