# Generated by Django 3.1.7 on 2021-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0013_auto_20210316_1130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique question of the para',
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='purportpara',
            unique_together={('shloka', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('para', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='shloka',
            unique_together={('book', 'canto', 'chapter', 'number')},
        ),
    ]
