# Generated by Django 3.1.7 on 2021-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0014_auto_20210316_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
