# Generated by Django 3.1.7 on 2021-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slokabase', '0002_auto_20210403_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='shloka',
            name='book',
            field=models.CharField(default='BG', max_length=20),
        ),
    ]
