# Generated by Django 3.1.7 on 2021-04-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slokabase', '0003_shloka_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shloka',
            unique_together={('book', 'canto', 'chapter', 'number')},
        ),
    ]
