# Generated by Django 3.1.7 on 2021-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slokabase', '0004_auto_20210403_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='purport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='translation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='w2w',
            field=models.TextField(),
        ),
    ]
