# Generated by Django 3.1.7 on 2021-04-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slokabase', '0005_auto_20210403_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='shloka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slokabase.shloka'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='slokabase.Theme'),
        ),
    ]
