# Generated by Django 3.1.7 on 2021-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slokabase', '0006_auto_20210404_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shloka',
            old_name='book',
            new_name='source',
        ),
        migrations.AddField(
            model_name='shloka',
            name='non_chapter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shloka',
            name='referance_text',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='canto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shloka',
            name='w2w',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shloka',
            unique_together={('source', 'canto', 'chapter', 'number')},
        ),
    ]
