# Generated by Django 3.1.7 on 2021-02-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Referance',
            fields=[
                ('referance_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('canto', models.IntegerField(blank=True, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('sloka', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('subtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionbase.answer')),
                ('referance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referance', to='questionbase.referance')),
                ('subtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtag', to='questionbase.subtag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='questionbase.tag')),
            ],
        ),
    ]
