# Generated by Django 3.1.7 on 2021-02-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='referance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionbase.referance', verbose_name='Referance'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtag',
        ),
        migrations.AddField(
            model_name='question',
            name='subtag',
            field=models.ManyToManyField(to='questionbase.SubTag'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='questionbase.Tag'),
        ),
    ]
