# Generated by Django 3.1.7 on 2021-02-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0002_auto_20210227_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbase.tag'),
        ),
    ]
