# Generated by Django 3.1.7 on 2021-02-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0004_auto_20210227_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbase.answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='referance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Referance', to='questionbase.referance'),
        ),
    ]
