# Generated by Django 3.1.7 on 2021-03-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0005_auto_20210227_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referance',
            name='non_chapter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referance',
            name='referance_text',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='referance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbase.referance'),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
