# Generated by Django 3.1.7 on 2021-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0006_auto_20210309_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='referance_text',
            field=models.CharField(max_length=20),
        ),
    ]
