# Generated by Django 3.1.7 on 2021-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0007_auto_20210309_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='referance_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
