# Generated by Django 3.1.7 on 2021-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbase', '0009_auto_20210310_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
